name: Generate Snake Game from GitHub Contributions

on:
  push:
    branches:
      - main  # Ana dal adınızı değiştirin (varsayılan olarak main)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Python sürümünüzü belirtin (Python 3.x önerilir)

    - name: Install dependencies
      run: pip install snakeware  # snakeware paketini yükleyin

    - name: Generate GitHub Contributions Snake Game
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          dist/github-snake.svg
          dist/github-snake-dark.svg?palette=github-dark
          dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
